import type { Theme } from '@skeletonlabs/skeleton/themes';

const ducks = {
  "name": "ducks",
  "properties": {
    "--type-scale-factor": "1.25",
    "--type-scale-1": "calc(0.75rem * var(--type-scale-factor))",
    "--type-scale-2": "calc(0.875rem * var(--type-scale-factor))",
    "--type-scale-3": "calc(1rem * var(--type-scale-factor))",
    "--type-scale-4": "calc(1.125rem * var(--type-scale-factor))",
    "--type-scale-5": "calc(1.25rem * var(--type-scale-factor))",
    "--type-scale-6": "calc(1.5rem * var(--type-scale-factor))",
    "--type-scale-7": "calc(1.875rem * var(--type-scale-factor))",
    "--type-scale-8": "calc(2.25rem * var(--type-scale-factor))",
    "--type-scale-9": "calc(3rem * var(--type-scale-factor))",
    "--type-scale-10": "calc(3.75rem * var(--type-scale-factor))",
    "--type-scale-11": "calc(4.5rem * var(--type-scale-factor))",
    "--type-scale-12": "calc(6rem * var(--type-scale-factor))",
    "--type-scale-13": "calc(8rem * var(--type-scale-factor))",
    "--base-font-color": "var(--color-surface-950)",
    "--base-font-color-dark": "var(--color-surface-50)",
    "--base-font-family": "Avenir, Montserrat, Corbel, URW Gothic, source-sans-pro, sans-serif",
    "--base-font-size": "14px",
    "--base-line-height": "inherit",
    "--base-font-weight": "300",
    "--base-font-style": "normal",
    "--base-letter-spacing": "0.025em",
    "--heading-font-color": "inherit",
    "--heading-font-color-dark": "inherit",
    "--heading-font-family": "Seravek, Gill Sans Nova, Ubuntu, Calibri, DejaVu Sans, source-sans-pro, sans-serif",
    "--heading-font-weight": "bold",
    "--heading-font-style": "normal",
    "--heading-letter-spacing": "0.025em",
    "--anchor-font-color": "var(--color-tertiary-600)",
    "--anchor-font-color-dark": "var(--color-tertiary-500)",
    "--anchor-font-family": "inherit",
    "--anchor-font-size": "inherit",
    "--anchor-line-height": "inherit",
    "--anchor-font-weight": "inherit",
    "--anchor-font-style": "inherit",
    "--anchor-letter-spacing": "inherit",
    "--anchor-text-decoration": "none",
    "--anchor-text-decoration-hover": "underline",
    "--anchor-text-decoration-active": "none",
    "--anchor-text-decoration-focus": "none",
    "--space-scale-factor": "1",
    "--radii-default": "6px",
    "--radii-container": "12px",
    "--border-width-default": "2px",
    "--divide-width-default": "2px",
    "--outline-width-default": "1px",
    "--ring-width-default": "2px",
    "--body-background-color": "255 255 255",
    "--body-background-color-dark": "var(--color-surface-900)",
    "--color-primary-50": "186 255 255",
    "--color-primary-100": "156 236 244",
    "--color-primary-200": "126 217 233",
    "--color-primary-300": "97 198 221",
    "--color-primary-400": "67 179 210",
    "--color-primary-500": "37 160 199",
    "--color-primary-600": "30 138 176",
    "--color-primary-700": "22 116 152",
    "--color-primary-800": "15 93 129",
    "--color-primary-900": "7 71 105",
    "--color-primary-950": "0 49 82",
    "--color-primary-contrast-dark": "var(--color-primary-950)",
    "--color-primary-contrast-light": "var(--color-primary-50)",
    "--color-primary-contrast-50": "var(--color-primary-contrast-dark)",
    "--color-primary-contrast-100": "var(--color-primary-contrast-dark)",
    "--color-primary-contrast-200": "var(--color-primary-contrast-dark)",
    "--color-primary-contrast-300": "var(--color-primary-contrast-dark)",
    "--color-primary-contrast-400": "var(--color-primary-contrast-dark)",
    "--color-primary-contrast-500": "var(--color-primary-contrast-dark)",
    "--color-primary-contrast-600": "var(--color-primary-contrast-light)",
    "--color-primary-contrast-700": "var(--color-primary-contrast-light)",
    "--color-primary-contrast-800": "var(--color-primary-contrast-light)",
    "--color-primary-contrast-900": "var(--color-primary-contrast-light)",
    "--color-primary-contrast-950": "var(--color-primary-contrast-light)",
    "--color-secondary-50": "255 224 198",
    "--color-secondary-100": "253 199 175",
    "--color-secondary-200": "251 173 151",
    "--color-secondary-300": "250 148 128",
    "--color-secondary-400": "248 122 104",
    "--color-secondary-500": "246 97 81",
    "--color-secondary-600": "218 78 65",
    "--color-secondary-700": "190 58 49",
    "--color-secondary-800": "163 39 32",
    "--color-secondary-900": "135 19 16",
    "--color-secondary-950": "107 0 0",
    "--color-secondary-contrast-dark": "0 0 0",
    "--color-secondary-contrast-light": "255 255 255",
    "--color-secondary-contrast-50": "var(--color-secondary-contrast-dark)",
    "--color-secondary-contrast-100": "var(--color-secondary-contrast-dark)",
    "--color-secondary-contrast-200": "var(--color-secondary-contrast-dark)",
    "--color-secondary-contrast-300": "var(--color-secondary-contrast-dark)",
    "--color-secondary-contrast-400": "var(--color-secondary-contrast-dark)",
    "--color-secondary-contrast-500": "var(--color-secondary-contrast-dark)",
    "--color-secondary-contrast-600": "var(--color-secondary-contrast-dark)",
    "--color-secondary-contrast-700": "var(--color-secondary-contrast-light)",
    "--color-secondary-contrast-800": "var(--color-secondary-contrast-light)",
    "--color-secondary-contrast-900": "var(--color-secondary-contrast-light)",
    "--color-secondary-contrast-950": "var(--color-secondary-contrast-light)",
    "--color-tertiary-50": "255 255 255",
    "--color-tertiary-100": "233 252 237",
    "--color-tertiary-200": "210 249 219",
    "--color-tertiary-300": "188 246 200",
    "--color-tertiary-400": "165 243 182",
    "--color-tertiary-500": "143 240 164",
    "--color-tertiary-600": "114 215 141",
    "--color-tertiary-700": "86 190 119",
    "--color-tertiary-800": "57 166 96",
    "--color-tertiary-900": "29 141 74",
    "--color-tertiary-950": "0 116 51",
    "--color-tertiary-contrast-dark": "0 0 0",
    "--color-tertiary-contrast-light": "var(--color-tertiary-50)",
    "--color-tertiary-contrast-50": "var(--color-tertiary-contrast-dark)",
    "--color-tertiary-contrast-100": "var(--color-tertiary-contrast-dark)",
    "--color-tertiary-contrast-200": "var(--color-tertiary-contrast-dark)",
    "--color-tertiary-contrast-300": "var(--color-tertiary-contrast-dark)",
    "--color-tertiary-contrast-400": "var(--color-tertiary-contrast-dark)",
    "--color-tertiary-contrast-500": "var(--color-tertiary-contrast-dark)",
    "--color-tertiary-contrast-600": "var(--color-tertiary-contrast-dark)",
    "--color-tertiary-contrast-700": "var(--color-tertiary-contrast-dark)",
    "--color-tertiary-contrast-800": "var(--color-tertiary-contrast-dark)",
    "--color-tertiary-contrast-900": "var(--color-tertiary-contrast-dark)",
    "--color-tertiary-contrast-950": "var(--color-tertiary-contrast-light)",
    "--color-success-50": "223 255 185",
    "--color-success-100": "195 248 159",
    "--color-success-200": "167 241 134",
    "--color-success-300": "139 234 108",
    "--color-success-400": "111 227 83",
    "--color-success-500": "83 220 57",
    "--color-success-600": "66 195 46",
    "--color-success-700": "50 171 34",
    "--color-success-800": "33 146 23",
    "--color-success-900": "17 122 11",
    "--color-success-950": "0 97 0",
    "--color-success-contrast-dark": "0 0 0",
    "--color-success-contrast-light": "var(--color-success-50)",
    "--color-success-contrast-50": "var(--color-success-contrast-dark)",
    "--color-success-contrast-100": "var(--color-success-contrast-dark)",
    "--color-success-contrast-200": "var(--color-success-contrast-dark)",
    "--color-success-contrast-300": "var(--color-success-contrast-dark)",
    "--color-success-contrast-400": "var(--color-success-contrast-dark)",
    "--color-success-contrast-500": "var(--color-success-contrast-dark)",
    "--color-success-contrast-600": "var(--color-success-contrast-dark)",
    "--color-success-contrast-700": "var(--color-success-contrast-dark)",
    "--color-success-contrast-800": "var(--color-success-contrast-dark)",
    "--color-success-contrast-900": "var(--color-success-contrast-light)",
    "--color-success-contrast-950": "var(--color-success-contrast-light)",
    "--color-warning-50": "255 255 194",
    "--color-warning-100": "255 237 170",
    "--color-warning-200": "255 218 145",
    "--color-warning-300": "255 200 121",
    "--color-warning-400": "255 181 96",
    "--color-warning-500": "255 163 72",
    "--color-warning-600": "228 140 58",
    "--color-warning-700": "201 118 43",
    "--color-warning-800": "173 95 29",
    "--color-warning-900": "146 73 14",
    "--color-warning-950": "119 50 0",
    "--color-warning-contrast-dark": "0 0 0",
    "--color-warning-contrast-light": "var(--color-warning-50)",
    "--color-warning-contrast-50": "var(--color-warning-contrast-dark)",
    "--color-warning-contrast-100": "var(--color-warning-contrast-dark)",
    "--color-warning-contrast-200": "var(--color-warning-contrast-dark)",
    "--color-warning-contrast-300": "var(--color-warning-contrast-dark)",
    "--color-warning-contrast-400": "var(--color-warning-contrast-dark)",
    "--color-warning-contrast-500": "var(--color-warning-contrast-dark)",
    "--color-warning-contrast-600": "var(--color-warning-contrast-dark)",
    "--color-warning-contrast-700": "var(--color-warning-contrast-dark)",
    "--color-warning-contrast-800": "var(--color-warning-contrast-light)",
    "--color-warning-contrast-900": "var(--color-warning-contrast-light)",
    "--color-warning-contrast-950": "var(--color-warning-contrast-light)",
    "--color-error-50": "255 172 146",
    "--color-error-100": "249 143 124",
    "--color-error-200": "243 114 102",
    "--color-error-300": "236 85 80",
    "--color-error-400": "230 56 58",
    "--color-error-500": "224 27 36",
    "--color-error-600": "197 22 29",
    "--color-error-700": "169 16 22",
    "--color-error-800": "142 11 14",
    "--color-error-900": "114 5 7",
    "--color-error-950": "87 0 0",
    "--color-error-contrast-dark": "0 0 0",
    "--color-error-contrast-light": "var(--color-error-50)",
    "--color-error-contrast-50": "var(--color-error-contrast-dark)",
    "--color-error-contrast-100": "var(--color-error-contrast-dark)",
    "--color-error-contrast-200": "var(--color-error-contrast-dark)",
    "--color-error-contrast-300": "var(--color-error-contrast-dark)",
    "--color-error-contrast-400": "var(--color-error-contrast-dark)",
    "--color-error-contrast-500": "var(--color-error-contrast-dark)",
    "--color-error-contrast-600": "var(--color-error-contrast-dark)",
    "--color-error-contrast-700": "var(--color-error-contrast-light)",
    "--color-error-contrast-800": "var(--color-error-contrast-light)",
    "--color-error-contrast-900": "var(--color-error-contrast-light)",
    "--color-error-contrast-950": "var(--color-error-contrast-light)",
    "--color-surface-50": "246 245 244",
    "--color-surface-100": "208 207 208",
    "--color-surface-200": "170 169 172",
    "--color-surface-300": "133 130 137",
    "--color-surface-400": "95 92 101",
    "--color-surface-500": "57 54 65",
    "--color-surface-600": "53 49 62",
    "--color-surface-700": "49 45 59",
    "--color-surface-800": "44 40 55",
    "--color-surface-900": "40 36 52",
    "--color-surface-950": "36 31 49",
    "--color-surface-contrast-dark": "var(--color-surface-950)",
    "--color-surface-contrast-light": "var(--color-surface-50)",
    "--color-surface-contrast-50": "var(--color-surface-contrast-dark)",
    "--color-surface-contrast-100": "var(--color-surface-contrast-dark)",
    "--color-surface-contrast-200": "var(--color-surface-contrast-dark)",
    "--color-surface-contrast-300": "var(--color-surface-contrast-dark)",
    "--color-surface-contrast-400": "var(--color-surface-contrast-light)",
    "--color-surface-contrast-500": "var(--color-surface-contrast-light)",
    "--color-surface-contrast-600": "var(--color-surface-contrast-light)",
    "--color-surface-contrast-700": "var(--color-surface-contrast-light)",
    "--color-surface-contrast-800": "var(--color-surface-contrast-light)",
    "--color-surface-contrast-900": "var(--color-surface-contrast-light)",
    "--color-surface-contrast-950": "var(--color-surface-contrast-light)"
  },
  "metadata": {
    "version": "3.0.0"
  }
} satisfies Theme;

export default ducks;
